INSERT INTO CATEGORIA(DESCRICAO) VALUES('PRODUTO DE LIMPEZA');
INSERT INTO CATEGORIA(DESCRICAO) VALUES('PRODUTO DE HIGIENE');
INSERT INTO CATEGORIA(DESCRICAO) VALUES('CURSOS');

INSERT INTO USUARIO(NOME, EMAIL, SENHA)VALUES('Bruno', 'BRUNO@', '12344');